### PR TITLE
Compatibility with Python 3

### PR DESCRIPTION
**Pull request by rubenwiersma**
I made some changes to make the codebase work with Python 3, which might be helpful for future researchers.

### CODE REVIEW

**Comment by yig** [comment]
Thank you! I created a branch for Python 2 and merged this into the main branch.

**Comment by yig** [comment]
It looks like a large OBJ file got added to the repos in this set of changes.

**Comment by rubenwiersma** [comment]
Oops, did you already remove it from the main branch, or would you like me to remove it?

**Comment by yig** [comment]
I removed it just now.

**Pull request merged**
